cms/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('logout', views.logout_view),
    path('<str:llave>', views.get_content),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('cms/', include('cms.urls')),
    path('admin/', admin.site.urls),
]

cms/models.py
from django.db import models

class Contenido(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()

    def __str__(self):
        return self.clave

class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField(blank=False)
    fecha = models.DateTimeField('publicado')

    def __str__(self):
        return self.titulo

cms/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.contrib.auth import logout

from .models import Contenido, Comentario

#usuario: meri
#contraseña: cursosweb

@csrf_exempt
def get_content(request, llave):
    if request.method == "PUT":
        valor = request.body.decode('utf-8')
    elif request.method == "POST":
        action = request.POST['action']
        if action == "Enviar Contenido":
            valor = request.POST['valor']
    if request.method == "PUT" or (request.method == "POST" and action == "Enviar Contenido"):
        try:
            c = Contenido.objects.get(clave=llave)
            c.valor = valor
        except Contenido.DoesNotExist:
            c = Contenido(clave=llave, valor=valor)
        c.save()
    if request.method == "POST" and action == "Enviar Comentario":
            c = get_object_or_404(Contenido, clave=llave)
            titulo = request.POST['titulo']
            cuerpo = request.POST['cuerpo']
            q = Comentario(contenido=c, titulo=titulo, cuerpo=cuerpo, fecha=timezone.now())
            q.save()

    contenido = get_object_or_404(Contenido, clave=llave)
    context = {'contenido': contenido, 'user': request.user}
    return render(request, 'cms/content.html', context)

@csrf_exempt
def index(request):
    content_list = Contenido.objects.all()
    context = {
        'content_list': content_list,
    }
    return render(request, 'cms/index.html', context)

def logout_view(request):
    logout(request)
    return redirect("/cms/")

cms/templates/cms/content.html
<h1>{{ contenido.valor }}</h1>
{% if user.is_authenticated %}
    <h2>Logged in as: {{user.username}}. <a href="/cms/logout">Logout</a></h2>
{% else %}
    <h2>Not logged in. <a href="/admin/">Login</a></h2>
{% endif %}
{% for comentario in contenido.comentario_set.all %}
    <hr>
    <h2>{{ comentario.titulo }}</h2><br>
        {{ comentario.cuerpo }}<br>
        Enviado el {{ comentario.fecha }}<br>
{% endfor %}
{% if user.is_authenticated %}

  <hr>
  <br>
  <form action="" method="POST">
    Introduce el (nuevo) contenido para esta página:
    <input type="text" name="valor">
    <input type="submit" name="action" value="Enviar Contenido">
  </form>

  <br>
  <form action="" method="POST">
    Introduce un nuevo comentario para esta página:
    <br>Título: <input type="text" name="titulo">
    <br>Cuerpo: <input type="text" name="cuerpo">
    <input type="submit" name="action" value="Enviar Comentario">
  </form>
{% endif %}

cms/templates/cms/index.html
{% if user.is_authenticated %}
    <h2>Logged in as: {{user.username}}. <a href="/cms/logout">Logout</a></h2>
{% else %}
    <h2>Not logged in. <a href="/admin/">Login</a></h2>
{% endif %}
{% if content_list %}
    <ul>
    {% for content in content_list %}
        <li><a href="/cms/{{ content.clave }}">{{ content.clave }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No contents are available.</p>
{% endif %}